name: Build and Release

on:
  # Trigger on semantic-version tag push, e.g. v1.2.3
  push:
    tags:
      - 'v*.*.*'
  # Allow manual runs
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      # 1. Check out your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install Repo Requirements
        run: pip install -r requirements.txt
        
      - name: Run build script
        run: .\build.bat

      - name: Zip build artifacts
        run: powershell Compress-Archive -Path '.\dist\*' -DestinationPath 'latest.zip'

      # - name: Create GitHub Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: latest
      #     release_name: Release latest
      #     body: |
      #       Automated release for tag `latest` from commit `${{ github.sha }}`.
      #     draft: false
      #     prerelease: false

      # 5. Upload the zip as a release asset
      - uses: IsaacShelton/update-existing-release@v1.3.4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release: "Latest"
          tag: "latest"
          replace: true
          files: >
            latest.zip
